
package seo.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWSA", targetNamespace = "com.seo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWSA {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "execute", targetNamespace = "com.seo", className = "seo.com.Execute")
    @ResponseWrapper(localName = "executeResponse", targetNamespace = "com.seo", className = "seo.com.ExecuteResponse")
    @Action(input = "com.seo/TestWSA/executeRequest", output = "com.seo/TestWSA/executeResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "com.seo/TestWSA/execute/Fault/IOException"),
        @FaultAction(className = Exception_Exception.class, value = "com.seo/TestWSA/execute/Fault/Exception")
    })
    public String execute(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception, IOException_Exception
    ;

}
