
package seo.com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWSB", targetNamespace = "com.seo", wsdlLocation = "http://localhost:8080/TestWS/TestWSB?wsdl")
public class TestWSB
    extends Service
{

    private final static URL TESTWSB_WSDL_LOCATION;
    private final static WebServiceException TESTWSB_EXCEPTION;
    private final static QName TESTWSB_QNAME = new QName("com.seo", "TestWSB");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TestWS/TestWSB?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWSB_WSDL_LOCATION = url;
        TESTWSB_EXCEPTION = e;
    }

    public TestWSB() {
        super(__getWsdlLocation(), TESTWSB_QNAME);
    }

    public TestWSB(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWSB_QNAME, features);
    }

    public TestWSB(URL wsdlLocation) {
        super(wsdlLocation, TESTWSB_QNAME);
    }

    public TestWSB(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWSB_QNAME, features);
    }

    public TestWSB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWSB(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWSA
     */
    @WebEndpoint(name = "TestWSPort")
    public TestWSA getTestWSPort() {
        return super.getPort(new QName("com.seo", "TestWSPort"), TestWSA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWSA
     */
    @WebEndpoint(name = "TestWSPort")
    public TestWSA getTestWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("com.seo", "TestWSPort"), TestWSA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWSB_EXCEPTION!= null) {
            throw TESTWSB_EXCEPTION;
        }
        return TESTWSB_WSDL_LOCATION;
    }

}
